#!/usr/bin/env python3
import json, sys, os, math, datetime
from pathlib import Path

NOW = datetime.datetime.now().isoformat()

if len(sys.argv) < 2:
    print("Usage: generate_1000_tasks.py PLAN_PATH")
    sys.exit(1)

plan_path = Path(sys.argv[1]).expanduser()
if not plan_path.exists():
    print(f"Plan not found: {plan_path}")
    sys.exit(1)

with plan_path.open("r") as f:
    plan = json.load(f)

plan_id = plan.get("plan_id", "unknown")
goal = plan.get("goal", "(no goal)")
steps = plan.get("steps", [])

if not steps:
    print("Plan has no steps; nothing to generate.")
    sys.exit(1)

tasks_root = Path(os.path.expanduser("~/tasks"))
incoming_dir = tasks_root / "incoming"
incoming_dir.mkdir(parents=True, exist_ok=True)

TOTAL_TASKS = 1000
num_steps = len(steps)
base_per_step = TOTAL_TASKS // num_steps
remainder = TOTAL_TASKS % num_steps

tasks = []
task_index_global = 0

for i, step in enumerate(steps):
    step_id = step.get("step_id", i + 1)
    step_title = step.get("title", f"Step {step_id}")
    step_obj = step.get("objective", "")
    # Distribute remaining tasks across first 'remainder' steps
    per_step = base_per_step + (1 if i < remainder else 0)

    for j in range(per_step):
        task_index_global += 1
        local_idx = j + 1
        task_id = f"{plan_id}-{step_id:02d}-{local_idx:03d}"

        # Slightly smarter titles
        title = f"S{step_id}.{local_idx:03d} - {step_title}"
        description = (
            f"Atomic task {local_idx} for step {step_id} ('{step_title}') "
            f"under plan {plan_id}. Objective focus: {step_obj}"
        )

        # Priority heuristic: first 100 tasks = high, next 300 = medium, rest = low
        if task_index_global <= 100:
            priority = "high"
        elif task_index_global <= 400:
            priority = "medium"
        else:
            priority = "low"

        task = {
            "task_id": task_id,
            "plan_id": plan_id,
            "step_id": step_id,
            "step_title": step_title,
            "goal": goal,
            "title": title,
            "description": description,
            "status": "pending",
            "priority": priority,
            "tags": [
                "sovereign-architect",
                "autogenerated",
                f"step-{step_id}",
            ],
            "created_at": NOW,
            "est_minutes": 25,
            "context": {
                "plan_path": str(plan_path),
                "step_objective": step_obj,
                "sequence_index": task_index_global,
                "local_step_index": local_idx,
            },
        }
        tasks.append(task)

if len(tasks) != TOTAL_TASKS:
    print(f"WARNING: Generated {len(tasks)} tasks, expected {TOTAL_TASKS}")

bundle = {
    "plan_id": plan_id,
    "goal": goal,
    "total_tasks": len(tasks),
    "generated_at": NOW,
    "source_plan_path": str(plan_path),
    "tasks": tasks,
}

out_path = incoming_dir / f"plan_{plan_id}_tasks_1000.json"
with out_path.open("w") as f:
    json.dump(bundle, f, indent=2)

print("Generated task bundle:")
print(f"  Plan ID:      {plan_id}")
print(f"  Goal:         {goal}")
print(f"  Total tasks:  {len(tasks)}")
print(f"  Output file:  {out_path}")
