#!/bin/bash
# YesQuid Task Worker - STRICT, NO-ILLUSION MODE
# Processes ONE task file and only marks it done if a real artifact exists.

set -euo pipefail

PLAN_ID="${1:-52f7b763}"

TASKS_ROOT="$HOME/tasks"
ACTIVE_DIR="$TASKS_ROOT/active/plan_${PLAN_ID}"
DONE_DIR="$TASKS_ROOT/done/plan_${PLAN_ID}"

OUTPUT_ROOT="$HOME/sovereign-architect/storage/outputs"
LOG_DIR="$OUTPUT_ROOT/logs"
ART_ROOT="$HOME/sovereign-architect/storage/artifacts/plan_${PLAN_ID}"

mkdir -p "$DONE_DIR" "$LOG_DIR" "$ART_ROOT"

if [ ! -d "$ACTIVE_DIR" ]; then
  echo "No active task directory at $ACTIVE_DIR"
  exit 0
fi

TASK_FILE="$(ls "$ACTIVE_DIR"/*.json 2>/dev/null | head -n 1 || true)"

if [ -z "${TASK_FILE}" ]; then
  echo "No tasks left in $ACTIVE_DIR"
  exit 0
fi

BASENAME="$(basename "$TASK_FILE")"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

# -------- strict validation --------
if ! jq empty "$TASK_FILE" >/dev/null 2>&1; then
  echo "ERROR: Invalid JSON in $TASK_FILE"
  exit 1
fi

TASK_ID="$(jq -r '.task_id // empty' "$TASK_FILE")"
TITLE="$(jq -r '.title // ""' "$TASK_FILE")"
PRIORITY="$(jq -r '.priority // ""' "$TASK_FILE")"
STEP_ID="$(jq -r '.step_id // ""' "$TASK_FILE")"
GOAL="$(jq -r '.goal // ""' "$TASK_FILE")"

if [ -z "$TASK_ID" ]; then
  echo "ERROR: task_id missing in $TASK_FILE"
  exit 1
fi

LOG_FILE="$LOG_DIR/${TASK_ID}_${TIMESTAMP}.log"
ART_DIR="$ART_ROOT/$TASK_ID"
mkdir -p "$ART_DIR"

{
  echo "Processing task: $TASK_FILE"
  echo "Task ID:   $TASK_ID"
  echo "Title:     $TITLE"
  echo "Priority:  $PRIORITY"
  echo "Step ID:   $STEP_ID"
  echo "Plan ID:   $PLAN_ID"
  echo "Artifacts: $ART_DIR"
} | tee "$LOG_FILE"

# -------- deterministic artifact creation --------
ART_FILE="$ART_DIR/${TASK_ID}.md"

if [ -f "$ART_FILE" ]; then
  echo "Artifact already exists: $ART_FILE" | tee -a "$LOG_FILE"
else
  {
    echo "# Artifact for task $TASK_ID"
    echo
    echo "- Plan ID:   $PLAN_ID"
    echo "- Step ID:   $STEP_ID"
    echo "- Title:     $TITLE"
    echo "- Priority:  $PRIORITY"
    echo "- Goal:      $GOAL"
    echo "- Created at: $(date -Iseconds)"
    echo
    echo "This is a deterministic, file-backed artifact generated by yesquid_task_worker."
    echo "If you want richer content, wire an LLM or codegen worker to extend this file."
  } > "$ART_FILE"
  echo "Created artifact: $ART_FILE" | tee -a "$LOG_FILE"
fi

# -------- invariant: no artifact => no 'done' --------
if ! find "$ART_DIR" -maxdepth 1 -type f | grep -q .; then
  echo "ERROR: No artifact files found in $ART_DIR" | tee -a "$LOG_FILE"
  echo "Task NOT marked done."
  exit 1
fi

# -------- move to done ONLY AFTER artifact check --------
mv "$TASK_FILE" "$DONE_DIR/"
echo "Task $TASK_ID moved to $DONE_DIR" | tee -a "$LOG_FILE"
echo "Worker complete." | tee -a "$LOG_FILE"
